2024-01-08 18:45:56 [scrapy.utils.log] INFO: Scrapy 2.11.0 started (bot: scraper)
2024-01-08 18:45:56 [scrapy.utils.log] INFO: Versions: lxml 5.0.1.0, libxml2 2.10.3, cssselect 1.2.0, parsel 1.8.1, w3lib 2.1.2, Twisted 22.10.0, Python 3.10.0 (tags/v3.10.0:b494f59, Oct  4 2021, 19:00:18) [MSC v.1929 64 bit (AMD64)], pyOpenSSL 23.3.0 (OpenSSL 3.1.4 24 Oct 2023), cryptography 41.0.7, Platform Windows-10-10.0.22621-SP0
2024-01-08 18:45:56 [scrapy.addons] INFO: Enabled addons:
[]
2024-01-08 18:45:56 [asyncio] DEBUG: Using selector: SelectSelector
2024-01-08 18:45:56 [scrapy.utils.log] DEBUG: Using reactor: twisted.internet.asyncioreactor.AsyncioSelectorReactor
2024-01-08 18:45:56 [scrapy.utils.log] DEBUG: Using asyncio event loop: asyncio.windows_events._WindowsSelectorEventLoop
2024-01-08 18:45:56 [scrapy.extensions.telnet] INFO: Telnet Password: 38ad5034cd499963
2024-01-08 18:45:56 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats']
2024-01-08 18:45:56 [scrapy.crawler] INFO: Overridden settings:
{'BOT_NAME': 'scraper',
 'FEED_EXPORT_ENCODING': 'utf-8',
 'LOG_FILE': 'pp.log',
 'NEWSPIDER_MODULE': 'scraper.spiders',
 'REQUEST_FINGERPRINTER_IMPLEMENTATION': '2.7',
 'ROBOTSTXT_OBEY': True,
 'SPIDER_MODULES': ['scraper.spiders'],
 'TWISTED_REACTOR': 'twisted.internet.asyncioreactor.AsyncioSelectorReactor'}
2024-01-08 18:45:57 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.robotstxt.RobotsTxtMiddleware',
 'scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2024-01-08 18:45:57 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2024-01-08 18:45:57 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2024-01-08 18:45:57 [scrapy.core.engine] INFO: Spider opened
2024-01-08 18:45:57 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2024-01-08 18:45:57 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2024-01-08 18:45:57 [scrapy-playwright] INFO: Starting download handler
2024-01-08 18:45:57 [scrapy-playwright] INFO: Starting download handler
2024-01-08 18:45:57 [asyncio] ERROR: Task exception was never retrieved
future: <Task finished name='Task-3' coro=<Connection.run() done, defined at C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py:268> exception=NotImplementedError()>
Traceback (most recent call last):
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 275, in run
    await self._transport.connect()
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_transport.py", line 135, in connect
    raise exc
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_transport.py", line 123, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1652, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 493, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
2024-01-08 18:45:57 [asyncio] ERROR: Task exception was never retrieved
future: <Task finished name='Task-4' coro=<Connection.run() done, defined at C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py:268> exception=NotImplementedError()>
Traceback (most recent call last):
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 275, in run
    await self._transport.connect()
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_transport.py", line 135, in connect
    raise exc
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_transport.py", line 123, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1652, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 493, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
2024-01-08 18:45:57 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method ScrapyPlaywrightDownloadHandler._engine_started of <scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler object at 0x0000026F31128F70>>
Traceback (most recent call last):
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapy_playwright\handler.py", line 143, in _launch
    self.playwright = await self.playwright_context_manager.start()
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\async_api\_context_manager.py", line 52, in start
    return await self.__aenter__()
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\async_api\_context_manager.py", line 47, in __aenter__
    playwright = AsyncPlaywright(next(iter(done)).result())
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 275, in run
    await self._transport.connect()
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_transport.py", line 135, in connect
    raise exc
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_transport.py", line 123, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1652, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 493, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
2024-01-08 18:45:57 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method ScrapyPlaywrightDownloadHandler._engine_started of <scrapy_playwright.handler.ScrapyPlaywrightDownloadHandler object at 0x0000026F31425B70>>
Traceback (most recent call last):
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapy_playwright\handler.py", line 143, in _launch
    self.playwright = await self.playwright_context_manager.start()
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\async_api\_context_manager.py", line 52, in start
    return await self.__aenter__()
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\async_api\_context_manager.py", line 47, in __aenter__
    playwright = AsyncPlaywright(next(iter(done)).result())
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 275, in run
    await self._transport.connect()
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_transport.py", line 135, in connect
    raise exc
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_transport.py", line 123, in connect
    self._proc = await asyncio.create_subprocess_exec(
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\asyncio\subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1652, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 493, in _make_subprocess_transport
    raise NotImplementedError
NotImplementedError
2024-01-08 18:46:02 [scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.myntra.com/robots.txt> (referer: None)
2024-01-08 18:46:02 [scrapy.core.scraper] ERROR: Error downloading <GET https://www.myntra.com/>
Traceback (most recent call last):
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\twisted\internet\defer.py", line 1693, in _inlineCallbacks
    result = context.run(
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\twisted\python\failure.py", line 518, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapy\core\downloader\middleware.py", line 54, in process_request
    return (yield download_func(request=request, spider=spider))
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapy_playwright\handler.py", line 314, in _download_request
    page = await self._create_page(request=request, spider=spider)
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapy_playwright\handler.py", line 236, in _create_page
    ctx_wrapper = await self._create_browser_context(
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapy_playwright\handler.py", line 195, in _create_browser_context
    await self._maybe_launch_browser()
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapy_playwright\handler.py", line 160, in _maybe_launch_browser
    logger.info("Launching browser %s", self.browser_type.name)
AttributeError: 'ScrapyPlaywrightDownloadHandler' object has no attribute 'browser_type'
2024-01-08 18:46:02 [scrapy.core.engine] INFO: Closing spider (finished)
2024-01-08 18:46:02 [scrapy.extensions.feedexport] INFO: Stored json feed (0 items) in: output.json
2024-01-08 18:46:02 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/exception_count': 1,
 'downloader/exception_type_count/builtins.AttributeError': 1,
 'downloader/request_bytes': 458,
 'downloader/request_count': 2,
 'downloader/request_method_count/GET': 2,
 'downloader/response_bytes': 1311,
 'downloader/response_count': 1,
 'downloader/response_status_count/200': 1,
 'elapsed_time_seconds': 5.35302,
 'feedexport/success_count/FileFeedStorage': 1,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2024, 1, 8, 13, 16, 2, 408383, tzinfo=datetime.timezone.utc),
 'httpcompression/response_bytes': 1614,
 'httpcompression/response_count': 1,
 'log_count/DEBUG': 4,
 'log_count/ERROR': 5,
 'log_count/INFO': 13,
 'response_received_count': 1,
 'robotstxt/request_count': 1,
 'robotstxt/response_count': 1,
 'robotstxt/response_status_count/200': 1,
 'scheduler/dequeued': 1,
 'scheduler/dequeued/memory': 1,
 'scheduler/enqueued': 1,
 'scheduler/enqueued/memory': 1,
 'start_time': datetime.datetime(2024, 1, 8, 13, 15, 57, 55363, tzinfo=datetime.timezone.utc)}
2024-01-08 18:46:02 [scrapy.core.engine] INFO: Spider closed (finished)
2024-01-08 18:46:02 [scrapy-playwright] INFO: Closing download handler
2024-01-08 18:46:02 [scrapy.utils.signal] ERROR: Error caught on signal handler: <bound method DownloadHandlers._close of <scrapy.core.downloader.handlers.DownloadHandlers object at 0x0000026F30F56590>>
Traceback (most recent call last):
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\twisted\internet\defer.py", line 1693, in _inlineCallbacks
    result = context.run(
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\twisted\python\failure.py", line 518, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapy\core\downloader\handlers\__init__.py", line 92, in _close
    yield dh.close()
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\twisted\internet\defer.py", line 1693, in _inlineCallbacks
    result = context.run(
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\twisted\python\failure.py", line 518, in throwExceptionIntoGenerator
    return g.throw(self.type, self.value, self.tb)
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapy_playwright\handler.py", line 293, in close
    yield deferred_from_coro(self._close())
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\twisted\internet\defer.py", line 1065, in adapt
    extracted = result.result()
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\scrapy_playwright\handler.py", line 302, in _close
    await self.playwright_context_manager.__aexit__()
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\async_api\_context_manager.py", line 58, in __aexit__
    await self._connection.stop_async()
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_connection.py", line 286, in stop_async
    self._transport.request_stop()
  File "C:\Users\adity\AppData\Local\Programs\Python\Python310\lib\site-packages\playwright\_impl\_transport.py", line 101, in request_stop
    assert self._output
AttributeError: 'PipeTransport' object has no attribute '_output'
